### ISSUE TITLE
undefined is not an object(evaluating 'NativeModule.CameraManager.Aspect')

### ISSUE THREAD

**Issue by shaikhussian** [applean/react-native-barcode-scanner-universal#1]
Hai when i try your repo, i got an error in  terminal like this,please help me how to solve this
![simulator screen shot 19-apr-2016 2 29 08 pm](https://cloud.githubusercontent.com/assets/11956308/14633448/42a0f684-063b-11e6-832f-2f4405b10be6.png)
please respond for it

**Comment by cpunion** [comment]
I forgot to write document. Can you try this steps?

```
npm install -g rnpm
rnpm link
```
It would link `react-native-camera` and `react-native-barcodescanner` native libraries into your project.

**Comment by shaikhussian** [comment]
in document usage part you didn't declare return()

**Comment by cpunion** [comment]
Thanks for your point. I would fix it.

Does your project work now?

**Comment by shaikhussian** [comment]
when i try it device it shows blank white screen may i know the reason for it

**Comment by cpunion** [comment]
It also has errors in README, rnpm don't link libraries in sub folder of this library, need run:
```
rnpm link react-native-camera
rnpm link react-native-barcodescanner
```
Then should works. I just tested it, it works fine.

**Comment by cpunion** [comment]
Added an tested example in newest commit, only iOS tested.

**Comment by cpunion** [comment]
Added android example, and publish 1.0.2.

**Comment by cpunion** [comment]
Thanks @shaikhussian
