### ISSUE TITLE
getting error when run in android

### ISSUE THREAD

**Issue by shaikhussian** [applean/react-native-barcode-scanner-universal#2]
hai when i try to run android devices in terminal it shows some error like this
![screen shot 2016-04-20 at 11 55 18 am](https://cloud.githubusercontent.com/assets/11956308/14665209/f41751f2-06ee-11e6-917d-ab30e7fc9fdc.png)
even i installed react-native-camera
can you please give me suggestions that hoe to solve it
please respond for it

**Comment by cpunion** [comment]
Please upgrade to 1.0.2, then remove `node_modules` and rerun `npm install`, also should run `rnpm link react-native-camera` and `rnpm link react-native-barcodescanner` to link the native libraries.

The reason is the newest `react-native-camera` is not compatible with `rnpm`, so we just reference it's master commit.

See: https://github.com/applean/react-native-barcode-scanner-universal#install

**Comment by shaikhussian** [comment]
Thank you for your response i have doubt that when i use it in ios, i got some problem, that i want to show the data of barcode in alert for that i wrote in my code like this
`class Barcode extends Component {
   constructor(props) {
    super(props);
    this.state = {
      qrcode:''
    };
  }
  render() {
    alert("render:"+this.state.qrcode);
    let scanArea = null
    if (Platform.OS === 'ios') {
      scanArea = (
        <View style={styles.rectangleContainer}>
          <View style={styles.rectangle} />
        </View>
      )
    }
    return (
      <BarcodeScanner
        onBarCodeRead={(code) => {
          this.setState({qrcode:code.data})
          console.log(code)
        }}
        style={styles.camera}>
        {scanArea}
      </BarcodeScanner>
    )
  }
}`
But the problem is alert is displaying multiple times,if possible can you please check my code and give me suggestions that if there is any wrong init
![img_5669](https://cloud.githubusercontent.com/assets/11956308/14670066/2d248fcc-0709-11e6-9526-83b6fa5842a4.jpg)
but in android it works fine, please respond

**Comment by cpunion** [comment]
That's expected behavior. Maybe it's different between `react-native-camera` (on iOS) and `react-native-barcodescanner` (on Android).

If you want be triggerred once, just add some code like this:
```
...
onBarCodeRead={(code) => {
  if (code.data != this.state.qrcode) {
    this.state({qrcode: code.data})
  }
}}
```

**Comment by shaikhussian** [comment]
Thank you it working fine

**Comment by shaikhussian** [comment]
it scans only qrcode when i try to scan barcode it not showing any result
